version: 'latest'

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=rocket_db
      - POSTGRES_PASSWORD=EUsouo21@
      - POSTGRES_DB=gestao_vagas